---
- name: Create 'afrodite' user
  user:
    name: afrodite
    password_lock: true
    generate_ssh_key: false
    shell: /bin/bash
- name: Limit sudo for 'afrodite' user
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^afrodite '
    line: "afrodite ALL=(ALL) NOPASSWD: \
      /usr/sbin/reboot, \
      /afrodite-server-tools/manager-tools/is-default-encryption-password.sh, \
      /afrodite-server-tools/manager-tools/change-encryption-password.sh, \
      /afrodite-server-tools/manager-tools/open-encryption.sh, \
      /afrodite-server-tools/manager-tools/close-encryption.sh, \
      /afrodite-server-tools/manager-tools/start-backend.sh, \
      /afrodite-server-tools/manager-tools/stop-backend.sh, \
      /afrodite-server-tools/manager-tools/print-logs.sh"
    validate: 'visudo -cf %s'
