---
- name: Add excecutable permissions to scripts in 'manager-tools' directory
  file:
    path: "../manager-tools/{{ item }}"
    mode: "+x"
  with_items:
    - secure-storage.sh
    - systemctl-access.sh
    - print-logs.sh
- name: Add excecutable permissions to scripts in 'tools' directory
  file:
    path: ../tools/{{ item }}
    mode: "+x"
  with_items:
    - update-country-ipset.sh
