---
- name: Set variables
  set_fact:
    fi_ip_list_name: fi_ip.txt
    ssh_ip_list_name: ssh_ip.txt
    manager_ip_list_name: manager_ip.txt

- name: Check if IP list for Finland already exists
  stat:
    path: "/home/afrodite/{{ fi_ip_list_name }}"
  register: fi_ip_stat
- name: Download IP list for Finland
  command:
    cmd: "python3 \
        ../setup-tools/download-ip-list.py \
        --file /home/afrodite/{{ fi_ip_list_name }} \
       --country fi"
  become: true
  become_user: afrodite
  when: fi_ip_stat.stat.exists == False

- name: Create 'country_fi' ipset
  command: "ipset -exist create country_fi hash:net"
- name: Setup 'country_fi' ipset
  command: "python3 ../setup-tools/setup-ipset.py \
        --file /home/afrodite/{{ fi_ip_list_name }} \
        --name country_fi"

- name: Create 'ssh_access' ipset
  command: "ipset -exist create ssh_access hash:net"
- name: Check if config for 'ssh_access' ipset exists
  stat:
    path: /afrodite-custom/{{ ssh_ip_list_name }}
  register: ssh_access_stat
- name: Setup 'ssh_access' ipset
  command: "python3 ../setup-tools/setup-ipset.py \
        --file /afrodite-custom/{{ ssh_ip_list_name }} \
        --name ssh_access"
  when: ssh_access_stat.stat.exists == True

- name: Create 'manager_access' ipset
  command: "ipset -exist create manager_access hash:net"
- name: Check if config for 'manager_access' ipset exists
  stat:
    path: /afrodite-custom/{{ manager_ip_list_name }}
  register: manager_access_stat
- name: Setup 'manager_access' ipset
  command: "python3 ../setup-tools/setup-ipset.py \
        --file /afrodite-custom/{{ manager_ip_list_name }} \
        --name manager_access"
  when: manager_access_stat.stat.exists == True

- name: Copy fail2ban config
  copy:
    src: ../files/fail2ban.local
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644

- name: Copy fail2ban jail config
  copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
