---
- name: Copy service files
  copy:
    src: ../services/
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Enable 'afrodite-manager' service
  systemd:
    name: afrodite-manager
    enabled: yes
- name: Enable 'afrodite-disable-swap' service
  systemd:
    name: afrodite-disable-swap
    enabled: yes
    state: started
# Disabled for now as latest IP country data for Finland from RIPE is from 2020
# - name: Enable 'afrodite-update-country-ipset' timer
#   systemd:
#     name: afrodite-update-country-ipset.timer
#     enabled: yes
#     state: started
