#cloud-config

# NOTE: if you use this init file replace
# - ssh_authorized_keys

packages:
  - ansible
  - git

ssh_pwauth: false
disable_root: true

sudo: false
lock_passwd: true
ssh_redirect_user: true

users:
  - name: afrodite_admin_user_with_ssh
    lock_passwd: true
    ssh_redirect_user: false
    # TODO
#   ssh_authorized_keys:
#     - key
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
