---
- name: Setup server
  hosts: localhost
  connection: local
  tasks:
  - name: Download dependencies
    include_tasks: tasks/apt-dependencies.yaml
  - name: Create users
    include_tasks: tasks/create-users.yaml
  - name: Setup services
    include_tasks: tasks/setup-services.yaml
  - name: Setup tool scripts
    include_tasks: tasks/setup-tool-scripts.yaml

  - name: Check if firewall setup is already done
    stat:
      path: "/afrodite-iptables"
    register: firewall_config_dir
  - name: Setup firewall
    include_tasks: tasks/setup-firewall.yaml
    when: firewall_config_dir.stat.exists == False
  - debug:
      msg: "Firewall setup is already done"
    when: firewall_config_dir.stat.exists == True

  - name: Setup encrypted filesystem
    include_tasks: tasks/setup-encrypted-fs.yaml

  - debug:
      msg: "Server setup is now complete"
