---
- name: Download and install app-manager
  hosts: localhost
  connection: local
  tasks:
    - name: Set variables
      set_fact:
        manager_url: http://localhost:5000
        api_key: password
    - name: Download encrypted app-manager binary
      get_url:
        url: "{{ manager_url }}/manager_api/latest_software?software_options=Manager&download_type=EncryptedBinary"
        dest: /tmp/app-manager-encrypted
        validate_certs: false
        headers:
          x-api-key: "{{ api_key }}"
    - name: Create binary directory
      file:
        path: /home/app/binaries
        state: directory
        owner: app
        group: app
        mode: 0755
    - name: Decrypt app-manager binary
      become: true
      become_user: app
      command:
        cmd: "gpg --output /home/app/binaries/app-manager \
          --decrypt /tmp/app-manager-encrypted"
    - name: Create app-manager working directory
      file:
        path: /home/app/manager-working-dir
        state: directory
        owner: app
        group: app
        mode: 0755
    - name: Set app-manager binary as executable
      file:
        path: /home/app/binaries/app-manager
        state: file
        owner: app
        group: app
        mode: u+x
